version: '3.7'

services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "test_db" ]
      interval: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5

  celery:
    build: .
    command: celery -A app.core.celery_config.celery_app worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    volumes:
      - .:/app

volumes:
  postgres_data:
